FROM archlinux:latest

WORKDIR /app

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm python python-pip python-virtualenv base-devel && \
    pacman -S --noconfirm git

RUN python -m venv /app/venv

RUN /app/venv/bin/pip install --upgrade pip

COPY main.py /app/
COPY requirements.txt /app/
COPY model_rf_word2vec.pkl /app/
COPY model_word2vec.pkl /app/

RUN /app/venv/bin/pip install -r requirements.txt

EXPOSE 7000

CMD ["/app/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000", "--reload"]
