FROM python:3.12-slim-bullseye

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    libopenblas-dev \
    liblapack-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN python -m venv /app/venv && \
    /app/venv/bin/pip install --upgrade pip setuptools wheel

COPY main.py /app/
COPY model_rf_word2vec.pkl /app/
COPY model_word2vec.pkl /app/

RUN /app/venv/bin/pip install --no-cache-dir --upgrade pip setuptools wheel numpy cython && \
    /app/venv/bin/pip install --no-cache-dir --upgrade --prefer-binary --no-build-isolation \
    -r requirements.txt

EXPOSE 7000

CMD ["/app/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000", "--reload"]
